apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: authenticator
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: registry.zouzland.com/authenticator:0.0.7
          name: authenticator
          env:
            - name: model_dir
              value: /opt/authenticator
            - name: K_SINK
              value: http://data-controller.default
            - name: THRESHOLD
              value: "0.25"
      imagePullSecrets:
        - name: regcred